# Generated by Django 3.2.11 on 2026-07-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '非遗类别',
                'verbose_name_plural': '非遗类别',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='保护单位名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
            ],
            options={
                'verbose_name': '保护单位',
                'verbose_name_plural': '保护单位',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='地区名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
            ],
            options={
                'verbose_name': '申报地区',
                'verbose_name_plural': '申报地区',
            },
        ),
        migrations.CreateModel(
            name='HeritageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('announcement_time', models.CharField(max_length=50, verbose_name='公布时间')),
                ('description', models.TextField(blank=True, verbose_name='项目简介')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='图片链接')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='所属类别')),
                ('protection_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.protectionunit', verbose_name='保护单位')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region', verbose_name='申报地区')),
            ],
            options={
                'verbose_name': '非遗项目',
                'verbose_name_plural': '非遗项目',
            },
        ),
    ]
