# Generated by Django 3.2.11 on 2026-07-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('name_key', models.CharField(blank=True, max_length=100, verbose_name='i18n名称key')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('description_en', models.TextField(blank=True, verbose_name='英文描述')),
                ('desc_key', models.CharField(blank=True, max_length=100, verbose_name='i18n描述key')),
                ('category_key', models.CharField(choices=[('catAccessory', '配饰'), ('catFabric', '织物'), ('catCeramic', '陶瓷'), ('catStationery', '文房'), ('catHome', '家居')], max_length=50, verbose_name='分类')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('image', models.CharField(max_length=500, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '文创周边',
                'verbose_name_plural': '文创周边',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='演出名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('name_key', models.CharField(blank=True, max_length=100, verbose_name='i18n名称key')),
                ('category_key', models.CharField(choices=[('categoryJingju', '京剧'), ('categoryKunqu', '昆曲'), ('categoryHuangmei', '黄梅戏'), ('categoryYueju', '越剧'), ('categoryGaojia', '高甲戏'), ('categoryChuanju', '川剧'), ('categoryYuju', '豫剧'), ('categoryOther', '其他')], max_length=50, verbose_name='分类')),
                ('datetime', models.DateTimeField(verbose_name='演出时间')),
                ('address', models.CharField(max_length=200, verbose_name='演出地点')),
                ('address_en', models.CharField(blank=True, max_length=200, verbose_name='英文地点')),
                ('address_key', models.CharField(blank=True, max_length=100, verbose_name='i18n地址key')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='票价')),
                ('image', models.CharField(max_length=500, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '票务演出',
                'verbose_name_plural': '票务演出',
                'ordering': ['datetime'],
            },
        ),
    ]
