# Generated by Django 3.2.11 on 2026-07-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类别名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '非遗类别',
                'verbose_name_plural': '非遗类别',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('name_key', models.CharField(blank=True, max_length=100, verbose_name='i18n名称key')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('description_en', models.TextField(blank=True, verbose_name='英文描述')),
                ('desc_key', models.CharField(blank=True, max_length=100, verbose_name='i18n描述key')),
                ('category_key', models.CharField(choices=[('catAccessory', '配饰'), ('catFabric', '织物'), ('catCeramic', '陶瓷'), ('catStationery', '文房'), ('catHome', '家居')], max_length=50, verbose_name='分类')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('image', models.CharField(max_length=500, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '文创周边',
                'verbose_name_plural': '文创周边',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='演出名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('name_key', models.CharField(blank=True, max_length=100, verbose_name='i18n名称key')),
                ('category_key', models.CharField(choices=[('categoryJingju', '京剧'), ('categoryKunqu', '昆曲'), ('categoryHuangmei', '黄梅戏'), ('categoryYueju', '越剧'), ('categoryGaojia', '高甲戏'), ('categoryChuanju', '川剧'), ('categoryYuju', '豫剧'), ('categoryOther', '其他')], max_length=50, verbose_name='分类')),
                ('datetime', models.DateTimeField(verbose_name='演出时间')),
                ('address', models.CharField(max_length=200, verbose_name='演出地点')),
                ('address_en', models.CharField(blank=True, max_length=200, verbose_name='英文地点')),
                ('address_key', models.CharField(blank=True, max_length=100, verbose_name='i18n地址key')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='票价')),
                ('image', models.CharField(max_length=500, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '票务演出',
                'verbose_name_plural': '票务演出',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='保护单位名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
            ],
            options={
                'verbose_name': '保护单位',
                'verbose_name_plural': '保护单位',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='地区名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
            ],
            options={
                'verbose_name': '申报地区',
                'verbose_name_plural': '申报地区',
            },
        ),
        migrations.CreateModel(
            name='HeritageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('announcement_time', models.CharField(max_length=50, verbose_name='公布时间')),
                ('description', models.TextField(blank=True, verbose_name='项目简介')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='图片链接')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.category', verbose_name='所属类别')),
                ('protection_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.protectionunit', verbose_name='保护单位')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.region', verbose_name='申报地区')),
            ],
            options={
                'verbose_name': '非遗项目',
                'verbose_name_plural': '非遗项目',
            },
        ),
    ]
