# Generated by Django 3.2.11 on 2026-07-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='desc_key',
            field=models.CharField(blank=True, max_length=100, verbose_name='i18n描述key'),
        ),
        migrations.AddField(
            model_name='performance',
            name='description',
            field=models.TextField(blank=True, verbose_name='演出描述'),
        ),
        migrations.AddField(
            model_name='performance',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='英文描述'),
        ),
    ]
